### ISSUE TITLE
forward loss: normalize the score vector before applying the transition matrix Q

### ISSUE THREAD

**Issue by murawaki** [takashiishida/comp#1]
The forward loss of Yu et al. (2018) assumes that the classifier g(x) outputs a probability vector with length K. In your implementation, `f`, the output of `linear_model` or `mlp_model`, is an unnormalized score vector. However, the `forward_loss` function directly applies the transition matrix `Q` to `f`, leading to a disparity between the algorithm and the implementation.
https://github.com/takashiishida/comp/blob/master/utils_algo.py#L37

**Comment by takashiishida** [comment]
Thank you for pointing this out.  I will check/update the code and get back to you soon.

**Comment by takashiishida** [comment]
I have fixed the forward loss.  I am also preparing an errata for the paper.  Thank you again for pointing this out!
