### ISSUE TITLE
non_negative_loss: ccp[k] instead of ccp?

### ISSUE THREAD

**Issue by RoyalSkye** [takashiishida/comp#2]
Hi authors:
Thanks for sharing your code. I have a question regarding your implementation of non_negative_loss. Based on the formulation (14) in your paper, should it be torch.mul(ccp[k], ...) instead of torch.mul(ccp, ...)? Refer to https://github.com/takashiishida/comp/blob/master/utils_algo.py#L23

Thanks in advance.

**Comment by takashiishida** [comment]
Hi @RoyalSkye sorry for my very late reply. You are right and I added [k] in 545c2a8f57c80ac62ebe4d0a3fd4e1f54a00bc13. Our paper only tried experiments with balanced datasets, but this may have a good effect if we use imbalanced datasets. Thank you for pointing this out!
